'use strict';

/**
 * Prepares public/ to run without a server (GitHub Pages, any static host):
 *   public/plan-data.js      the plan as window.CISSP_PLAN
 *   public/xlsx-lite.js      copy of the Excel library (browser build is the same file)
 *   public/tracker-model.js  copy of the workbook layout shared with the server
 *
 * Run after editing plan.js, xlsx-lite.js or tracker-model.js:  node build-static.js
 * The outputs are committed so GitHub Pages needs no build step.
 */

const fs = require('fs');
const path = require('path');
const PLAN = require('./plan');

const pub = path.join(__dirname, 'public');
fs.writeFileSync(
  path.join(pub, 'plan-data.js'),
  '// Generated by build-static.js from plan.js — do not edit by hand.\n' +
  'window.CISSP_PLAN = ' + JSON.stringify(PLAN) + ';\n'
);
for (const f of ['xlsx-lite.js', 'tracker-model.js']) {
  fs.copyFileSync(path.join(__dirname, f), path.join(pub, f));
}
console.log('static assets written to public/');

// GitHub Pages copy: <repo root>/cissp/ is what https://<user>.github.io/<repo>/cissp/ serves
// when Pages is set to "Deploy from a branch" (main, / root). Keep it a byte-for-byte mirror.
const pages = path.join(__dirname, '..', 'cissp');
fs.rmSync(pages, { recursive: true, force: true });
fs.mkdirSync(pages, { recursive: true });
for (const f of fs.readdirSync(pub)) fs.copyFileSync(path.join(pub, f), path.join(pages, f));
fs.writeFileSync(path.join(pages, '.nojekyll'), '');
console.log('GitHub Pages copy written to ../cissp/');
